### ISSUE TITLE
Error when close fridge and fix

### ISSUE THREAD

**Issue by Svenhr** [PenguScript/qb-limeysjob#4]
SCRIPT ERROR: @qb-inventory/server/main.lua:859: attempt to index a nil value (field '?˙)

also item not saved in fridge due to this error can you fix it thx

**Comment by Svenhr** [comment]
Found problem in qb-limeysjob client/ main.lua at line 122

Found

TriggerServerEvent("inventory:server:OpenInventory", "stash", "fridge", { line 122

replate with

TriggerServerEvent("inventory:server:OpenInventory", "stash", "winefridge", {

**Comment by PenguScript** [comment]
resolved
