### ISSUE TITLE
Something is wrong don't no what. Cheers!

### ISSUE THREAD

**Issue by wichertp** [PenguScript/qb-limeysjob#6]
i followed the readme but something is causing isseus. Also when eating the food in doesnt change hungry state or drink state.
Might be ralated to the isseu am having!

[script:qb-smallresou] SCRIPT ERROR: @qb-smallresources/server/entities.lua:6: attempt to index a nil value (global 'Config')
[script:qb-smallresou] > handler (@qb-smallresources/server/entities.lua:6)

**Comment by PenguScript** [comment]
I don't believe thats a me issue. Go throught the readme please!
